# Generated by Django 4.2.16 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_created_at_category_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "user", "type"), name="unique_user_category_per_type"
            ),
        ),
    ]
